"""
Exporter Module

Handles exporting generated content to various formats and files.
"""

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from ..config import Config, get_config, OutputFormat
from ..analyzers.project_analyzer import ProjectAnalysis


@dataclass
class GeneratedContent:
    """Container for all generated content."""
    er_diagram: str = ""
    dfd: str = ""
    flowcharts: str = ""
    documentation: str = ""
    raw_analysis: Optional[ProjectAnalysis] = None


class Exporter:
    """Exports generated content to files."""
    
    def __init__(self, config: Optional[Config] = None):
        self.config = config or get_config()
    
    def export_all(self, content: GeneratedContent) -> list[str]:
        """Export all generated content to files."""
        output_dir = Path(self.config.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        created_files = []
        
        # Export ER diagram
        if content.er_diagram:
            er_path = output_dir / "er_diagram.md"
            self._write_diagram(er_path, "Entity-Relationship Diagram", content.er_diagram)
            created_files.append(str(er_path))
        
        # Export DFD
        if content.dfd:
            dfd_path = output_dir / "dfd.md"
            self._write_diagram(dfd_path, "Data Flow Diagram", content.dfd)
            created_files.append(str(dfd_path))
        
        # Export flowcharts
        if content.flowcharts:
            fc_path = output_dir / "flowcharts.md"
            self._write_content(fc_path, "# Process Flowcharts\n\n" + content.flowcharts)
            created_files.append(str(fc_path))
        
        # Export documentation
        if content.documentation:
            doc_path = output_dir / "documentation.md"
            self._write_content(doc_path, content.documentation)
            created_files.append(str(doc_path))
        
        # Export raw analysis as JSON
        if content.raw_analysis:
            json_path = output_dir / "models_analysis.json"
            self._write_json(json_path, content.raw_analysis.to_dict())
            created_files.append(str(json_path))
        
        # Create index file
        index_path = output_dir / "index.md"
        self._write_index(index_path, created_files, content)
        created_files.insert(0, str(index_path))
        
        return created_files
    
    def _write_diagram(self, path: Path, title: str, content: str) -> None:
        """Write a diagram file with Mermaid wrapper."""
        # Check if content already has mermaid wrapper
        if "```mermaid" in content:
            full_content = f"# {title}\n\n{content}"
        else:
            full_content = f"# {title}\n\n```mermaid\n{content}\n```"
        
        self._write_content(path, full_content)
    
    def _write_content(self, path: Path, content: str) -> None:
        """Write content to a file."""
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
    
    def _write_json(self, path: Path, data: dict) -> None:
        """Write JSON data to a file."""
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)
    
    def _write_index(
        self,
        path: Path,
        files: list[str],
        content: GeneratedContent,
    ) -> None:
        """Write an index file linking to all generated content."""
        lines = [
            "# Generated Documentation Index",
            "",
            f"Generated documentation for Django project.",
            "",
            "## Contents",
            "",
        ]
        
        if content.raw_analysis:
            analysis = content.raw_analysis
            lines.extend([
                "### Project Summary",
                "",
                f"- **Apps**: {len(analysis.apps)}",
                f"- **Models**: {analysis.total_models}",
                f"- **Fields**: {analysis.total_fields}",
                f"- **Relationships**: {analysis.total_relationships}",
                "",
            ])
        
        lines.append("### Generated Files")
        lines.append("")
        
        for file_path in files:
            if file_path == str(path):
                continue
            
            filename = os.path.basename(file_path)
            lines.append(f"- [{filename}](./{filename})")
        
        lines.extend([
            "",
            "---",
            "",
            "*Generated by Django Documentation Generator*",
        ])
        
        self._write_content(path, "\n".join(lines))


def export_content(content: GeneratedContent, config: Optional[Config] = None) -> list[str]:
    """Export generated content to files."""
    exporter = Exporter(config)
    return exporter.export_all(content)
